import { createClient } from "@/lib/supabase/server"
import { NextResponse } from "next/server"

export const dynamic = "force-dynamic"
export const runtime = "nodejs"

export async function POST() {
  try {
    const supabase = await createClient()

    // Načítaj referencie z databázy
    const { data: countries } = await supabase
      .from("countries")
      .select("id, name_sk")
      .in("code", ["SK", "CZ", "AT", "DE", "PL", "HU"])

    const { data: professionGroups } = await supabase.from("profession_groups").select("id, name_sk").limit(30)

    if (!countries || !professionGroups) {
      return NextResponse.json({ error: "Failed to load reference data" }, { status: 500 })
    }

    const countryMap = Object.fromEntries(countries.map((c) => [c.name_sk, c.id]))
    const getSKCountry = () => countryMap["Slovensko"]
    const getRandomCountries = () => {
      const sk = countryMap["Slovensko"]
      const others = countries.filter((c) => c.name_sk !== "Slovensko")
      const randomOther = others[Math.floor(Math.random() * others.length)]
      return [sk, randomOther.id]
    }

    // 20 IT/Office kandidátov
    const itCandidates = [
      {
        first_name: "Martin",
        last_name: "Kováč",
        email: "martin.kovac.test@example.sk",
        phone: "+421901234567",
        date_of_birth: "1990-03-15",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups.find((p) => p.name_sk.includes("IT"))?.id || professionGroups[0].id,
        years_of_experience: 8,
        expected_salary: 3200,
        available_from: "2025-02-01",
        languages: { en: "C1", sk: "native", de: "B1" },
        cv_summary: { role: "Full-Stack Developer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Petra",
        last_name: "Nováková",
        email: "petra.novakova.test@example.sk",
        phone: "+421902345678",
        date_of_birth: "1995-07-22",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups.find((p) => p.name_sk.includes("IT"))?.id || professionGroups[1].id,
        years_of_experience: 4,
        expected_salary: 2400,
        available_from: "2025-03-01",
        languages: { en: "B2", sk: "native" },
        cv_summary: { role: "Frontend Developer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Ján",
        last_name: "Horváth",
        email: "jan.horvath.test@example.sk",
        phone: "+421903456789",
        date_of_birth: "1988-11-30",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[2].id,
        years_of_experience: 10,
        expected_salary: 3600,
        available_from: "2025-01-15",
        languages: { en: "C1", sk: "native", de: "B2" },
        cv_summary: { role: "Backend Developer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Eva",
        last_name: "Tóthová",
        email: "eva.tothova.test@example.sk",
        phone: "+421904567890",
        date_of_birth: "1992-05-18",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[3].id,
        years_of_experience: 6,
        expected_salary: 2800,
        available_from: "2025-02-15",
        languages: { en: "B2", sk: "native" },
        cv_summary: { role: "DevOps Engineer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Michal",
        last_name: "Baláž",
        email: "michal.balaz.test@example.sk",
        phone: "+421905678901",
        date_of_birth: "1997-09-10",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[4].id,
        years_of_experience: 2,
        expected_salary: 1600,
        available_from: "2025-04-01",
        languages: { en: "B1", sk: "native" },
        cv_summary: { role: "Junior QA Engineer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Zuzana",
        last_name: "Varga",
        email: "zuzana.varga.test@example.sk",
        phone: "+421906789012",
        date_of_birth: "1991-02-28",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[5].id,
        years_of_experience: 7,
        expected_salary: 3000,
        available_from: "2025-02-01",
        languages: { en: "C1", sk: "native", de: "A2" },
        cv_summary: { role: "UX/UI Designer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Tomáš",
        last_name: "Molnár",
        email: "tomas.molnar.test@example.sk",
        phone: "+421907890123",
        date_of_birth: "1994-06-12",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[6].id,
        years_of_experience: 5,
        expected_salary: 2600,
        available_from: "2025-03-15",
        languages: { en: "B2", sk: "native" },
        cv_summary: { role: "Project Manager", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Lucia",
        last_name: "Kiss",
        email: "lucia.kiss.test@example.sk",
        phone: "+421908901234",
        date_of_birth: "1993-08-05",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[7].id,
        years_of_experience: 6,
        expected_salary: 2700,
        available_from: "2025-02-20",
        languages: { en: "C1", sk: "native", de: "B1" },
        cv_summary: { role: "Data Analyst", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Matej",
        last_name: "Gašpar",
        email: "matej.gaspar.test@example.sk",
        phone: "+421909012345",
        date_of_birth: "1996-12-20",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[8].id,
        years_of_experience: 3,
        expected_salary: 2000,
        available_from: "2025-05-01",
        languages: { en: "B2", sk: "native" },
        cv_summary: { role: "Mobile Developer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Simona",
        last_name: "Szabó",
        email: "simona.szabo.test@example.sk",
        phone: "+421900123456",
        date_of_birth: "1989-04-17",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[9].id,
        years_of_experience: 9,
        expected_salary: 3400,
        available_from: "2025-01-20",
        languages: { en: "C1", sk: "native", de: "B2" },
        cv_summary: { role: "Senior Frontend Developer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Andrej",
        last_name: "Lukáč",
        email: "andrej.lukac.test@example.sk",
        phone: "+421911234567",
        date_of_birth: "1998-01-25",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[10].id,
        years_of_experience: 1,
        expected_salary: 1200,
        available_from: "2025-06-01",
        languages: { en: "B1", sk: "native" },
        cv_summary: { role: "Junior Developer", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Nikola",
        last_name: "Takáč",
        email: "nikola.takac.test@example.sk",
        phone: "+421912345678",
        date_of_birth: "1990-10-08",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[11].id,
        years_of_experience: 8,
        expected_salary: 3100,
        available_from: "2025-02-10",
        languages: { en: "C1", sk: "native" },
        cv_summary: { role: "Business Analyst", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Filip",
        last_name: "Urban",
        email: "filip.urban.test@example.sk",
        phone: "+421913456789",
        date_of_birth: "1995-03-14",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[12].id,
        years_of_experience: 4,
        expected_salary: 2300,
        available_from: "2025-03-20",
        languages: { en: "B2", sk: "native", de: "A2" },
        cv_summary: { role: "Marketing Specialist", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Katarína",
        last_name: "Balog",
        email: "katarina.balog.test@example.sk",
        phone: "+421914567890",
        date_of_birth: "1992-07-03",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[13].id,
        years_of_experience: 6,
        expected_salary: 2500,
        available_from: "2025-02-25",
        languages: { en: "C1", sk: "native", de: "B1" },
        cv_summary: { role: "HR Specialist", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Jakub",
        last_name: "Farkaš",
        email: "jakub.farkas.test@example.sk",
        phone: "+421915678901",
        date_of_birth: "1997-11-19",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[14].id,
        years_of_experience: 2,
        expected_salary: 1800,
        available_from: "2025-04-15",
        languages: { en: "B2", sk: "native" },
        cv_summary: { role: "Sales Representative", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Monika",
        last_name: "Papp",
        email: "monika.papp.test@example.sk",
        phone: "+421916789012",
        date_of_birth: "1991-05-27",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[15].id,
        years_of_experience: 7,
        expected_salary: 2900,
        available_from: "2025-02-05",
        languages: { en: "C1", sk: "native", de: "B2" },
        cv_summary: { role: "Accountant", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Dávid",
        last_name: "Nagy",
        email: "david.nagy.test@example.sk",
        phone: "+421917890123",
        date_of_birth: "1994-09-11",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[16].id,
        years_of_experience: 5,
        expected_salary: 2400,
        available_from: "2025-03-10",
        languages: { en: "B2", sk: "native" },
        cv_summary: { role: "Content Creator", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Veronika",
        last_name: "Oláh",
        email: "veronika.olah.test@example.sk",
        phone: "+421918901234",
        date_of_birth: "1996-02-16",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[17].id,
        years_of_experience: 3,
        expected_salary: 2100,
        available_from: "2025-04-20",
        languages: { en: "B1", sk: "native", de: "A2" },
        cv_summary: { role: "Customer Support", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Marek",
        last_name: "Bodnár",
        email: "marek.bodnar.test@example.sk",
        phone: "+421919012345",
        date_of_birth: "1993-12-04",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[18].id,
        years_of_experience: 6,
        expected_salary: 2800,
        available_from: "2025-02-28",
        languages: { en: "C1", sk: "native", de: "B1" },
        cv_summary: { role: "System Administrator", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Lenka",
        last_name: "Kovács",
        email: "lenka.kovacs.test@example.sk",
        phone: "+421920123456",
        date_of_birth: "1999-08-23",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[19].id,
        years_of_experience: 1,
        expected_salary: 1400,
        available_from: "2025-07-01",
        languages: { en: "B1", sk: "native" },
        cv_summary: { role: "Junior Graphic Designer", typ_prace: "Zamestnanie na plný úväzok" },
      },
    ]

    // 20 Remeslá kandidátov
    const craftCandidates = [
      {
        first_name: "Peter",
        last_name: "Novák",
        email: "peter.novak.test@example.sk",
        phone: "+421921234567",
        date_of_birth: "1985-04-12",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups.find((p) => p.name_sk.includes("elektr"))?.id || professionGroups[20].id,
        years_of_experience: 12,
        expected_salary: 2800,
        available_from: "2025-02-01",
        languages: { sk: "native", de: "B1" },
        cv_summary: { role: "Elektrikár", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Ján",
        last_name: "Varga",
        email: "jan.varga.test@example.sk",
        phone: "+421922345678",
        date_of_birth: "1988-06-25",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[21].id,
        years_of_experience: 10,
        expected_salary: 2600,
        available_from: "2025-03-01",
        languages: { sk: "native", de: "A2" },
        cv_summary: { role: "Murár", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Milan",
        last_name: "Horák",
        email: "milan.horak.test@example.sk",
        phone: "+421923456789",
        date_of_birth: "1983-09-18",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[22].id,
        years_of_experience: 15,
        expected_salary: 3200,
        available_from: "2025-01-15",
        languages: { sk: "native", de: "B2", en: "A2" },
        cv_summary: { role: "Stolár", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Jozef",
        last_name: "Tóth",
        email: "jozef.toth.test@example.sk",
        phone: "+421924567890",
        date_of_birth: "1990-11-07",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[23].id,
        years_of_experience: 8,
        expected_salary: 2400,
        available_from: "2025-02-15",
        languages: { sk: "native", de: "B1" },
        cv_summary: { role: "Zvárač", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Štefan",
        last_name: "Baláž",
        email: "stefan.balaz.test@example.sk",
        phone: "+421925678901",
        date_of_birth: "1992-01-30",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[24].id,
        years_of_experience: 6,
        expected_salary: 2200,
        available_from: "2025-03-15",
        languages: { sk: "native", de: "A2" },
        cv_summary: { role: "Inštalatér", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Vladimír",
        last_name: "Molnár",
        email: "vladimir.molnar.test@example.sk",
        phone: "+421926789012",
        date_of_birth: "1987-05-22",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[25].id,
        years_of_experience: 11,
        expected_salary: 2700,
        available_from: "2025-02-01",
        languages: { sk: "native", de: "B1", en: "A1" },
        cv_summary: { role: "Zámočník", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Miroslav",
        last_name: "Kiss",
        email: "miroslav.kiss.test@example.sk",
        phone: "+421927890123",
        date_of_birth: "1995-08-14",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[26].id,
        years_of_experience: 4,
        expected_salary: 1900,
        available_from: "2025-04-01",
        languages: { sk: "native", de: "A2" },
        cv_summary: { role: "Maliar", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Róbert",
        last_name: "Gašpar",
        email: "robert.gaspar.test@example.sk",
        phone: "+421928901234",
        date_of_birth: "1991-03-09",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[27].id,
        years_of_experience: 7,
        expected_salary: 2300,
        available_from: "2025-02-20",
        languages: { sk: "native", de: "B1" },
        cv_summary: { role: "Klampiar", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Ladislav",
        last_name: "Szabó",
        email: "ladislav.szabo.test@example.sk",
        phone: "+421929012345",
        date_of_birth: "1984-12-28",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[28].id,
        years_of_experience: 13,
        expected_salary: 3000,
        available_from: "2025-01-20",
        languages: { sk: "native", de: "B2", en: "A2" },
        cv_summary: { role: "Tesár", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Pavol",
        last_name: "Lukáč",
        email: "pavol.lukac.test@example.sk",
        phone: "+421930123456",
        date_of_birth: "1994-07-16",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[29].id,
        years_of_experience: 5,
        expected_salary: 2100,
        available_from: "2025-03-20",
        languages: { sk: "native", de: "A2" },
        cv_summary: { role: "Mechanik", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Igor",
        last_name: "Takáč",
        email: "igor.takac.test@example.sk",
        phone: "+421931234567",
        date_of_birth: "1998-02-11",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[20].id,
        years_of_experience: 2,
        expected_salary: 1500,
        available_from: "2025-05-01",
        languages: { sk: "native" },
        cv_summary: { role: "Junior Elektrikár", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Branislav",
        last_name: "Urban",
        email: "branislav.urban.test@example.sk",
        phone: "+421932345678",
        date_of_birth: "1986-10-05",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[21].id,
        years_of_experience: 12,
        expected_salary: 2900,
        available_from: "2025-02-10",
        languages: { sk: "native", de: "B1", en: "A1" },
        cv_summary: { role: "Stavbyvedúci", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Dušan",
        last_name: "Balog",
        email: "dusan.balog.test@example.sk",
        phone: "+421933456789",
        date_of_birth: "1993-04-19",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[22].id,
        years_of_experience: 6,
        expected_salary: 2300,
        available_from: "2025-03-05",
        languages: { sk: "native", de: "A2" },
        cv_summary: { role: "Truhlár", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Roman",
        last_name: "Farkaš",
        email: "roman.farkas.test@example.sk",
        phone: "+421934567890",
        date_of_birth: "1989-09-24",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[23].id,
        years_of_experience: 9,
        expected_salary: 2600,
        available_from: "2025-02-15",
        languages: { sk: "native", de: "B1" },
        cv_summary: { role: "Senior Zvárač", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Rastislav",
        last_name: "Papp",
        email: "rastislav.papp.test@example.sk",
        phone: "+421935678901",
        date_of_birth: "1996-06-03",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[24].id,
        years_of_experience: 3,
        expected_salary: 1800,
        available_from: "2025-04-15",
        languages: { sk: "native" },
        cv_summary: { role: "Junior Inštalatér", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Marcel",
        last_name: "Nagy",
        email: "marcel.nagy.test@example.sk",
        phone: "+421936789012",
        date_of_birth: "1987-11-17",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[25].id,
        years_of_experience: 11,
        expected_salary: 2800,
        available_from: "2025-02-01",
        languages: { sk: "native", de: "B2", en: "A2" },
        cv_summary: { role: "Zámočník - Kovoobrábač", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Radoslav",
        last_name: "Oláh",
        email: "radoslav.olah.test@example.sk",
        phone: "+421937890123",
        date_of_birth: "1992-02-28",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[26].id,
        years_of_experience: 7,
        expected_salary: 2400,
        available_from: "2025-03-01",
        languages: { sk: "native", de: "B1" },
        cv_summary: { role: "Maliar - Natierač", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Bohuslav",
        last_name: "Bodnár",
        email: "bohuslav.bodnar.test@example.sk",
        phone: "+421938901234",
        date_of_birth: "1997-08-08",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[27].id,
        years_of_experience: 2,
        expected_salary: 1600,
        available_from: "2025-06-01",
        languages: { sk: "native", de: "A1" },
        cv_summary: { role: "Junior Klampiar", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Slavomír",
        last_name: "Kovács",
        email: "slavomir.kovacs.test@example.sk",
        phone: "+421939012345",
        date_of_birth: "1985-05-13",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[28].id,
        years_of_experience: 14,
        expected_salary: 3100,
        available_from: "2025-01-25",
        languages: { sk: "native", de: "B2", en: "B1" },
        cv_summary: { role: "Senior Tesár", typ_prace: "Zamestnanie na plný úväzok" },
      },
      {
        first_name: "Juraj",
        last_name: "Lakatos",
        email: "juraj.lakatos.test@example.sk",
        phone: "+421940123456",
        date_of_birth: "1991-12-01",
        nationality_id: getSKCountry(),
        residence_country_id: getSKCountry(),
        work_country_preferences: getRandomCountries(),
        profession_group_id: professionGroups[29].id,
        years_of_experience: 8,
        expected_salary: 2500,
        available_from: "2025-02-20",
        languages: { sk: "native", de: "B1", en: "A1" },
        cv_summary: { role: "Auto Mechanik", typ_prace: "Zamestnanie na plný úväzok" },
      },
    ]

    const allCandidates = [...itCandidates, ...craftCandidates]

    // Vlož kandidátov po jednom (batch insert môže zlyhať)
    const results = []
    for (const candidate of allCandidates) {
      const { data, error } = await supabase
        .from("candidate_profiles")
        .insert(candidate)
        .select("id, first_name, last_name, email")
        .single()

      if (error) {
        console.error(`Failed to insert ${candidate.email}:`, error)
      } else {
        results.push(data)
      }
    }

    return NextResponse.json({
      success: true,
      message: `Successfully created ${results.length} out of ${allCandidates.length} candidates`,
      candidates: results,
    })
  } catch (error: any) {
    console.error("Seed error:", error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
